import type { NextPage } from 'next';
import styles from '../styles/Home.module.css';
import classNames from 'classnames';
import Image from 'next/image';
import Logo from '../assets/MazeMakerLogo.png';
import Feature from '../components/Feature';
import Link from 'next/link';


const Home: NextPage = () => {
  return (
    <div id="root">
      <div id="topBar" className={classNames(styles.topBar, styles.darkBackground)}>
        <div className={classNames(styles.image)}><Image src={Logo} alt='Maze Maker Logo' /></div>
        <p>MazeMaker</p>
      </div>
      <div id="content" className={classNames(styles.darkBackground, styles.content)}>
        <div id="description" className={classNames(styles.description)}>
          <h1 id="descriptionHeader" className={classNames(styles.descriptionHeader)}>Create Free Custom Mazes</h1>
          <h2 id="descriptionText" className={classNames(styles.descriptionText)}>Create and edit autogenerated Mazes or from Scratch</h2>
          <Link href="/editor">
            <button id="getStartedBtn" className={classNames(styles.mainBtn)}>Get Started</button>
          </Link>
        </div>
        <div id="featureDiv" className={classNames(styles.featureDiv)}>
          <h2 id="featuresHeading" className={classNames(styles.featuresHeading)}>Features</h2>
          <div id="featureUnderline" className={classNames(styles.featureUnderline)} />
          <div id="featureList" className={classNames(styles.featureList)}>
            <Feature image='/images/featureImages/ChangeWallSize_ColdBlue.png' altText="Changing wall size example image">Custom Wall Size</Feature>
            <Feature image='/images/featureImages/AutoGenMazeBold_ColdBlue.png' altText="Autogenerated maze example image">Autogenerated Random Mazes</Feature>
            <Feature image='/images/featureImages/ImageInsideMaze_ColdBlue.png' altText="Image inside maze example image">Supports Images inside Maze</Feature>
            <Feature image='/images/featureImages/SolvabilityOptimalSolution_ColdBlue.png' altText="Checking maze solvability example image">Checks Solvability and Optimal Solution on the fly</Feature>
            <Feature image='/images/featureImages/Export_ColdBlue.png' altText="Exporting Maze to Image exameple image">Export Mazes to PNG, JPEG, and SVG</Feature>
            <Feature image='/images/featureImages/Watermark_ColdBlue.png' altText="Watermark example image">Add Custom Watermark</Feature>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home;
